### ISSUE TITLE
Automatically add `///` after doc comments

### ISSUE THREAD

**Issue by PgBiel** [nathanjcollins/zed-fsharp#1]
Hi!

I would like to request support for adding `///` automatically when pressing enter while in a doc comment, just as a convenience.

It is worth noting that this extension already seems to support this feature for regular comments (`// stuff`), just not doc comments (`/// stuff`, regardless of whether they contain XML).

Here is a comparison between how VSCode (Ionide) and Zed (this extension) do it:

https://github.com/nathanjcollins/zed-fsharp/assets/9021226/5b68c5a7-378e-4c41-b21e-4385916891da

https://github.com/nathanjcollins/zed-fsharp/assets/9021226/166d0833-43ba-4708-acbe-d703ae51cece

Let me know if you need help, I could try my hand at a PR.

Thanks!

**Comment by nathanjcollins** [comment]
Hey @PgBiel, thanks for the suggestion! I've added this (see PR above) - you can either manually install the extension update or wait for my PR on the zed-extensions branch here to be merged: https://github.com/zed-industries/extensions/pull/1023

**Comment by PgBiel** [comment]
Working nicely, thank you!!
